//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STG_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolTeacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SchoolTeacher()
        {
            this.UnavaliableHours = new HashSet<UnavaliableHours>();
        }
    
        public int Id { get; set; }
        public int SchoolId { get; set; }
        public int TeacherId { get; set; }
    
        public virtual School School { get; set; }
        public virtual Teacher Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnavaliableHours> UnavaliableHours { get; set; }
    }
}
