//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STG_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timetable
    {
        public int Id { get; set; }
        public short Size { get; set; }
        public short Part { get; set; }
        public string Day { get; set; }
        public string Hour { get; set; }
        public int SchoolId { get; set; }
        public string GroupSubjectTeacherSemester { get; set; }
        public int GroupSubjectTeacherTeacherId { get; set; }
        public int GroupSubjectTeacherGroupId { get; set; }
        public int GroupSubjectTeacherSubjectId { get; set; }
        public int RoomId { get; set; }
    
        public virtual School School { get; set; }
        public virtual GroupSubjectTeacher GroupSubjectTeacher { get; set; }
        public virtual Room Room { get; set; }
    }
}
