//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STG_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnavaliableHours
    {
        public int SchoolTeacherId { get; set; }
        public string Year { get; set; }
        public string Semester { get; set; }
        public string Hours { get; set; }
    
        public virtual SchoolTeacher SchoolTeacher { get; set; }
    }
}
